   CREATE TABLE QCIB_KOTAK_ACK_HEDR 
   (	"UNIQUEID" DECIMAL(19,0) NOT NULL, 
	"MESSAGE_ID" VARCHAR(100), 
	"STATUS_CODE" VARCHAR(50), 
	"STATUS_REMARK" VARCHAR(100), 
	 PRIMARY KEY ("UNIQUEID"));
   

   CREATE TABLE QCIB_KOTAK_FAULT 
   (	"UNIQUEID" DECIMAL(19,0) NOT NULL, 
	"CODE" VARCHAR(50), 
	"REASON" VARCHAR(100), 
	"FAULT_ID" DECIMAL(19,0), 
	 PRIMARY KEY ("FAULT_ID"));

   

  CREATE TABLE QCIB_KOTAK_INST_ENRICHMENT
   (	"KOTK_INST_ENRICH_ID" DECIMAL(19,0) NOT NULL, 
	"ENRICHMENT" VARCHAR(255), 
	"UNIQUEID" DECIMAL(19,0), 
	 PRIMARY KEY ("KOTK_INST_ENRICH_ID"));
    
   

 CREATE TABLE QCIB_KOTAK_PAY_INSTRUMENT 
   (	REQUEST_UNIQUE_ID DECIMAL(19,0) NOT NULL, 
	INST_REF_NO VARCHAR(100), 
	COMPANY_ID VARCHAR(50), 
	COMP_BATCH_ID VARCHAR(50), 
	CONFIDENTIAL_IND VARCHAR(50), 
	MY_PROD_CODE VARCHAR(50), 
	COMP_TRANS_NO VARCHAR(100), 
	PAY_MODE VARCHAR(100), 
	TXN_AMNT VARCHAR(100), 
	ACCOUNT_NO VARCHAR(100), 
	DR_REF_NMBR VARCHAR(100), 
	DR_DESC VARCHAR(255), 
	PAYMENT_DT VARCHAR(50), 
	BANK_CD_IND VARCHAR(100), 
	BENE_BNK_CD VARCHAR(100), 
	REC_BR_CD VARCHAR(100), 
	BENE_ACCT_NO VARCHAR(100), 
	BENE_NAME VARCHAR(255), 
	BENE_CODE VARCHAR(80), 
	BENE_EMAIL VARCHAR(100), 
	BENE_FAX VARCHAR(80), 
	BENE_MB VARCHAR(80), 
	BENE_ADDR1 VARCHAR(255), 
	BENE_ADDR2 VARCHAR(255), 
	BENE_ADDR3 VARCHAR(255), 
	BENE_ADDR4 VARCHAR(255), 
	BENE_ADDR5 VARCHAR(255), 
	CITY VARCHAR(100), 
	ZIP VARCHAR(50), 
	COUNTRY VARCHAR(100), 
	STATE VARCHAR(100), 
	TELEPHONE_NO VARCHAR(50), 
	BENE_ID VARCHAR(50), 
	BENE_TAX_ID VARCHAR(50), 
	AUTH_PERSON VARCHAR(100), 
	AUTH_PERSON_ID VARCHAR(50), 
	DELIVERY_MODE VARCHAR(100), 
	PAY_OUT_LOC VARCHAR(100), 
	PICK_UP_BR VARCHAR(100), 
	PAYMENT_REF VARCHAR(100), 
	CHG_BORNE_BYV VARCHAR(100), 
	INST_DT VARCHAR(50), 
	MICR_NO VARCHAR(50), 
	CREDIT_REF_NO VARCHAR(100), 
	PAYMENT_DTL VARCHAR(100), 
	PAYMENT_DTL1 VARCHAR(100), 
	PAYMENT_DTL2 VARCHAR(100), 
	PAYMENT_DTL3 VARCHAR(100), 
	MAIL_TO_ADDR1 VARCHAR(100), 
	MAIL_TO_ADDR2 VARCHAR(100), 
	MAIL_TO_ADDR3 VARCHAR(100), 
	MAIL_TO_ADDR4 VARCHAR(100), 
	MAIL_TO VARCHAR(100), 
	EXCH_DOC VARCHAR(100), 
	INST_CHECK_SUM VARCHAR(100), 
	INST_RF1 VARCHAR(100), 
	INST_RF2 VARCHAR(100), 
	INST_RF3 VARCHAR(100), 
	INST_RF4 VARCHAR(100), 
	INST_RF5 VARCHAR(100), 
	INST_RF6 VARCHAR(100), 
	INST_RF7 VARCHAR(100), 
	INST_RF8 VARCHAR(100), 
	INST_RF9 VARCHAR(100), 
	INST_RF10 VARCHAR(100), 
	INST_RF11 VARCHAR(100), 
	INST_RF12 VARCHAR(100), 
	INST_RF13 VARCHAR(100), 
	INST_RF14 VARCHAR(100), 
	INST_RF15 VARCHAR(100), 
	 PRIMARY KEY (REQUEST_UNIQUE_ID));
	 	 
   
   
    CREATE TABLE QCIB_KOTAK_REQ_PAY_HDR 
   (	REQUEST_UNIQUE_ID DECIMAL(19,0) NOT NULL, 
	MESSAGE_ID VARCHAR(50), 
	MSG_SOURCE VARCHAR(50), 
	CLIENT_CODE VARCHAR(500), 
	BATCH_REF_NMBR VARCHAR(50), 
	HEADER_CHECKSUM VARCHAR(50), 
	REQ_RF1 VARCHAR(50), 
	REQ_RF2 VARCHAR(50), 
	REQ_RF3 VARCHAR(50), 
	REQ_RF4 VARCHAR(50), 
	REQ_RF5 VARCHAR(50), 
	 PRIMARY KEY (REQUEST_UNIQUE_ID));
	 	 
   
     CREATE TABLE QCIB_KOTAK_REQ_REV_DTL 
   (	REQUEST_UNIQUE_ID DECIMAL(19,0) NOT NULL, 
	MESSAGE_ID VARCHAR(50), 
	 PRIMARY KEY (REQUEST_UNIQUE_ID));
   	 
    CREATE TABLE QCIB_KOTAK_REQ_REV_HDR 
   (	REQUEST_UNIQUE_ID DECIMAL(19,0) NOT NULL, 
	REQUEST_ID VARCHAR(50), 
	MSG_SOURCE VARCHAR(50), 
	CLIENT_CODE VARCHAR(50), 
	DATE_POST VARCHAR(50), 
	 PRIMARY KEY (REQUEST_UNIQUE_ID));
	 	 
   

      CREATE TABLE QCIB_KOTAK_REQ_RES 
   (	EID BIGINT, 
	UNIQUEID VARCHAR(100), 
	REQUEST VARCHAR(max), 
	RESPONSE VARCHAR(max), 
	CREATED DATETIME2 (6), 
	APPID VARCHAR(50), 
	DESCRIPTION VARCHAR(1000), 
	CORELATIONID VARCHAR(250), 
	TOKEN VARCHAR(250), 
	STATUS VARCHAR(250), 
	TAG VARCHAR(250), 
	UPDATED_TIME DATETIME2 (6), 
	PDFPATH VARCHAR(200), 
	INTERNAL_REQ VARCHAR(max), 
	INTERNAL_RES VARCHAR(max), 
	PRICE VARCHAR(50) DEFAULT 0, 
	DT_CREATED DATETIME DEFAULT getdate() NOT NULL, 
	IS_PUSHED VARCHAR(300) DEFAULT 'PENDING' NOT NULL, 
	MIFIN_DT_UPDATE DATETIME2 (6), 
	MIFIN_STATUS VARCHAR(50), 
	MIFIN_MESSAGE VARCHAR(300), 
	 CONSTRAINT KOTAK_REQ_RES_PK PRIMARY KEY (UNIQUEID));
	 
   
   CREATE TABLE QCIB_KOTAK_SUB 
   (	EID BIGINT, 
	UNIQUEID VARCHAR(100), 
	REQUEST VARCHAR(max), 
	RESPONSE VARCHAR(max), 
	CREATED DATETIME2 (6), 
	APPID VARCHAR(50), 
	DESCRIPTION VARCHAR(1000), 
	CORELATIONID VARCHAR(250), 
	TOKEN VARCHAR(250), 
	STATUS VARCHAR(250), 
	TAG VARCHAR(250), 
	UPDATED_TIME DATETIME2 (6), 
	PDFPATH VARCHAR(200), 
	INTERNAL_REQ VARCHAR(max), 
	INTERNAL_RES VARCHAR(max), 
	PRICE VARCHAR(50) DEFAULT 0, 
	DT_CREATED DATETIME DEFAULT getdate() NOT NULL, 
	IS_PUSHED VARCHAR(300) DEFAULT 'PENDING' NOT NULL, 
	MIFIN_DT_UPDATE DATETIME2 (6), 
	MIFIN_STATUS VARCHAR(50), 
	MIFIN_MESSAGE VARCHAR(300), 
	 CONSTRAINT KOTAK_SUB_PK PRIMARY KEY (UNIQUEID));
	 
  



 CREATE TABLE QCIB_KOTK_REV_DTL 
   (	KOTK_REV_DTL_ID DECIMAL(19,0) NOT NULL, 
	MESSAGE_ID VARCHAR(50), 
	STATUS_CODE VARCHAR(50), 
	STATUS_DESCRIPTION VARCHAR(500), 
	UTR VARCHAR(50), 
	UNIQUEID DECIMAL(19,0), 
	 PRIMARY KEY (KOTK_REV_DTL_ID));
   	 
   
  CREATE TABLE QCIB_KOTK_REV_HDR 
   (	REQUEST_UNIQUE_ID DECIMAL(19,0) NOT NULL, 
	REQUEST_ID VARCHAR(50), 
	MSG_SOURCE VARCHAR(50), 
	CLIENT_CODE VARCHAR(50), 
	DATE_POST VARCHAR(50), 
	 PRIMARY KEY (REQUEST_UNIQUE_ID));
   	 

CREATE TABLE QCIB_SCHEDULAR_TRACK
   (	"SCHEDULARID" VARCHAR(50) NOT NULL, 
	"SCHEDULARNAME" VARCHAR(100) NOT NULL, 
	"SCHEDULARSTATE" VARCHAR(500) NOT NULL, 
	"INITIATEDBY" VARCHAR(100), 
	"STARTTIME" DATETIME2 (6), 
	"ENDTIME" DATETIME2 (6)
   );
  

CREATE TABLE QCIB_AUTH_VALIDATION 
   (	"ID" VARCHAR(100), 
	"APPID" VARCHAR(250), 
	"TOKEN" VARCHAR(250), 
	"SERVICES" VARCHAR(250), 
	"CREATED" VARCHAR(50), 
	"EXPIRYDATE" DATETIME, 
	"STATUS" VARCHAR(50)
   ) ;
  

CREATE TABLE QM_SYS_IB_CONFIGURATION
   (	"CONFIGID" BIGINT NOT NULL, 
	"APPLICATIONNAME" VARCHAR(50), 
	"PARAMID" BIGINT, 
	"PARAMNAME" VARCHAR(50), 
	"PARAMVALUE" VARCHAR(500), 
	"CREATEDBY" BIGINT, 
	"CREATED_DATETIME" DATETIME, 
	"UPDATEBY" BIGINT, 
	"UPDATE_DATETIME" DATETIME, 
	"STATUS" VARCHAR(1), 
	"MAKER_ID" BIGINT, 
	"MAKER_DATE" DATETIME, 
	"MAKER_REMARKS" VARCHAR(50), 
	"MAKER_SYSDATE" DATETIME, 
	"AUTH_ID" BIGINT, 
	"AUTH_DATE" DATETIME, 
	"AUTH_REMARK" VARCHAR(500), 
	"AUTH_SYSDATE" DATETIME, 
	 CONSTRAINT "QM_SYS_IB_CONFIG_PK" PRIMARY KEY ("CONFIGID"));

     
---------------------------------------sequences------------------------------



   CREATE SEQUENCE  QCIB_KOTAK_ENRICH_SEQ   INCREMENT BY 1 START WITH 110 ;
   CREATE SEQUENCE  QCIB_KOTAK_FAULT_SEQ    INCREMENT BY 1 START WITH 160 ;
   CREATE SEQUENCE  QCIB_KOTAK_MAIN_SQC     INCREMENT BY 1 START WITH 260 ;
   CREATE SEQUENCE  QCIB_KOTK_REV_DTL_SEQ   INCREMENT BY 1 START WITH 160 ;
   CREATE SEQUENCE  QCIB_KOTK_REV_HDR_SEQ   INCREMENT BY 1 START WITH 105 ;


-------------------------INSERT AUTH_VALIDATION------------------------


Insert into QCIB_AUTH_VALIDATION  (ID,APPID,TOKEN,SERVICES,CREATED,EXPIRYDATE,STATUS) values ('10','KARZA','f4b10aac-e9c2-4bf5-8c8e-31bee316dd8d','KARZA','03-JAN-18','2022-10-11','Y');
Insert into QCIB_AUTH_VALIDATION  (ID,APPID,TOKEN,SERVICES,CREATED,EXPIRYDATE,STATUS) values ('10','CREDIT','fcdf1e96-4a3b-43d7-b8bb-af659f775b96','CREDIT','01-DEC-17','2022-11-29','Y');
Insert into QCIB_AUTH_VALIDATION  (ID,APPID,TOKEN,SERVICES,CREATED,EXPIRYDATE,STATUS) values ('10','EXPO','e98632e4-f111-432a-9e57-616a4f6d7b93','EXPERIAN','01-MAR-18','2022-03-30','Y');
Insert into QCIB_AUTH_VALIDATION  (ID,APPID,TOKEN,SERVICES,CREATED,EXPIRYDATE,STATUS) values ('10','tets','bcfe50b3-f294-4ce0-abab-366bee7d032b','KOTAK','16-MAR-18','2022-03-31','Y');
Insert into QCIB_AUTH_VALIDATION  (ID,APPID,TOKEN,SERVICES,CREATED,EXPIRYDATE,STATUS) values ('10','test2','31f0241d-5b2e-41c5-bd85-9aef7d060fca','CRIF FUSION','16-MAR-18','2022-03-23','Y');


Insert into QM_SYS_IB_CONFIGURATION (CONFIGID,APPLICATIONNAME,PARAMID,PARAMNAME,PARAMVALUE,CREATEDBY,CREATED_DATETIME,UPDATEBY,UPDATE_DATETIME,STATUS,MAKER_ID,MAKER_DATE,MAKER_REMARKS,MAKER_SYSDATE,AUTH_ID,AUTH_DATE,AUTH_REMARK,AUTH_SYSDATE) values (1000000000,'QC_IB',1000000000,'PropertyFilePath','D:\\opt\\Logger\\',null,null,null,null,'Y',null,null,null,null,null,null,'Loger Path',null);
Insert into QM_SYS_IB_CONFIGURATION (CONFIGID,APPLICATIONNAME,PARAMID,PARAMNAME,PARAMVALUE,CREATEDBY,CREATED_DATETIME,UPDATEBY,UPDATE_DATETIME,STATUS,MAKER_ID,MAKER_DATE,MAKER_REMARKS,MAKER_SYSDATE,AUTH_ID,AUTH_DATE,AUTH_REMARK,AUTH_SYSDATE) values (1000000001,'QC_IB',1000000001,'spring.enable.proxy.development','N',null,null,null,null,'Y',null,null,null,null,null,null,'Enable Proxy',null);
Insert into QM_SYS_IB_CONFIGURATION (CONFIGID,APPLICATIONNAME,PARAMID,PARAMNAME,PARAMVALUE,CREATEDBY,CREATED_DATETIME,UPDATEBY,UPDATE_DATETIME,STATUS,MAKER_ID,MAKER_DATE,MAKER_REMARKS,MAKER_SYSDATE,AUTH_ID,AUTH_DATE,AUTH_REMARK,AUTH_SYSDATE) values (1000000002,'QC_IB',1000000002,'com.qc.proxy.ip','cachecluster.qualtechedge.com',null,null,null,null,'Y',null,null,null,null,null,null,'Proxy IP',null);
Insert into QM_SYS_IB_CONFIGURATION (CONFIGID,APPLICATIONNAME,PARAMID,PARAMNAME,PARAMVALUE,CREATEDBY,CREATED_DATETIME,UPDATEBY,UPDATE_DATETIME,STATUS,MAKER_ID,MAKER_DATE,MAKER_REMARKS,MAKER_SYSDATE,AUTH_ID,AUTH_DATE,AUTH_REMARK,AUTH_SYSDATE) values (1000000003,'QC_IB',1000000003,'com.qc.proxy.port','3128',null,null,null,null,'Y',null,null,null,null,null,null,'Proxy Port',null);
Insert into QM_SYS_IB_CONFIGURATION (CONFIGID,APPLICATIONNAME,PARAMID,PARAMNAME,PARAMVALUE,CREATEDBY,CREATED_DATETIME,UPDATEBY,UPDATE_DATETIME,STATUS,MAKER_ID,MAKER_DATE,MAKER_REMARKS,MAKER_SYSDATE,AUTH_ID,AUTH_DATE,AUTH_REMARK,AUTH_SYSDATE) values (1000000004,'QC_IB',1000000004,'com.qc.enable.proxy.call','N',null,null,null,null,'Y',null,null,null,null,null,null,'Enable Proxy in Perfios',null);
Insert into QM_SYS_IB_CONFIGURATION (CONFIGID,APPLICATIONNAME,PARAMID,PARAMNAME,PARAMVALUE,CREATEDBY,CREATED_DATETIME,UPDATEBY,UPDATE_DATETIME,STATUS,MAKER_ID,MAKER_DATE,MAKER_REMARKS,MAKER_SYSDATE,AUTH_ID,AUTH_DATE,AUTH_REMARK,AUTH_SYSDATE) values (1000000005,'QC_IB',1000000005,'com.qc.file.storage','D:\\opt\\Logger\\VersionFiles',null,null,null,null,'Y',null,null,null,null,null,null,'File Storage Path in Admin',null);
Insert into QM_SYS_IB_CONFIGURATION (CONFIGID,APPLICATIONNAME,PARAMID,PARAMNAME,PARAMVALUE,CREATEDBY,CREATED_DATETIME,UPDATEBY,UPDATE_DATETIME,STATUS,MAKER_ID,MAKER_DATE,MAKER_REMARKS,MAKER_SYSDATE,AUTH_ID,AUTH_DATE,AUTH_REMARK,AUTH_SYSDATE) values (1000000006,'QC_IB',1000000006,'com.qc.hardCoded','N',null,null,null,null,'Y',null,null,null,null,null,null,'File Storage Path in Admin',null);
Insert into QM_SYS_IB_CONFIGURATION (CONFIGID,APPLICATIONNAME,PARAMID,PARAMNAME,PARAMVALUE,CREATEDBY,CREATED_DATETIME,UPDATEBY,UPDATE_DATETIME,STATUS,MAKER_ID,MAKER_DATE,MAKER_REMARKS,MAKER_SYSDATE,AUTH_ID,AUTH_DATE,AUTH_REMARK,AUTH_SYSDATE) values (1200000001,'QC_IB_KOTAK',1200000001,'com.kotak.pdf.save','D:\\opt\\Logger\\KotakPdf',null,null,null,null,'Y',null,null,null,null,null,null,'NA',null);
Insert into QM_SYS_IB_CONFIGURATION (CONFIGID,APPLICATIONNAME,PARAMID,PARAMNAME,PARAMVALUE,CREATEDBY,CREATED_DATETIME,UPDATEBY,UPDATE_DATETIME,STATUS,MAKER_ID,MAKER_DATE,MAKER_REMARKS,MAKER_SYSDATE,AUTH_ID,AUTH_DATE,AUTH_REMARK,AUTH_SYSDATE) values (1200000002,'QC_IB_KOTAK',1200000002,'com.kotak.reversal.action','application/soap+xml;charset=UTF-8;action=/BusinessServices/StarterProcesses/CMS_Generic_Service.serviceagent/Reversal',null,null,null,null,'Y',null,null,null,null,null,null,'NA',null);
Insert into QM_SYS_IB_CONFIGURATION (CONFIGID,APPLICATIONNAME,PARAMID,PARAMNAME,PARAMVALUE,CREATEDBY,CREATED_DATETIME,UPDATEBY,UPDATE_DATETIME,STATUS,MAKER_ID,MAKER_DATE,MAKER_REMARKS,MAKER_SYSDATE,AUTH_ID,AUTH_DATE,AUTH_REMARK,AUTH_SYSDATE) values (1200000003,'QC_IB_KOTAK',1200000003,'com.kotak.payment.action','application/soap+xml;charset=UTF-8;action=/BusinessServices/StarterProcesses/CMS_Generic_Service.serviceagent/Payment',null,null,null,null,'Y',null,null,null,null,null,null,'NA',null);
Insert into QM_SYS_IB_CONFIGURATION (CONFIGID,APPLICATIONNAME,PARAMID,PARAMNAME,PARAMVALUE,CREATEDBY,CREATED_DATETIME,UPDATEBY,UPDATE_DATETIME,STATUS,MAKER_ID,MAKER_DATE,MAKER_REMARKS,MAKER_SYSDATE,AUTH_ID,AUTH_DATE,AUTH_REMARK,AUTH_SYSDATE) values (1200000004,'QC_IB_KOTAK',1200000004,'com.kotak.3rdParty.url','https://apigwuat.kotak.com:8443/cms_generic_service',null,null,null,null,'Y',null,null,null,null,null,null,'NA',null);
Insert into QM_SYS_IB_CONFIGURATION (CONFIGID,APPLICATIONNAME,PARAMID,PARAMNAME,PARAMVALUE,CREATEDBY,CREATED_DATETIME,UPDATEBY,UPDATE_DATETIME,STATUS,MAKER_ID,MAKER_DATE,MAKER_REMARKS,MAKER_SYSDATE,AUTH_ID,AUTH_DATE,AUTH_REMARK,AUTH_SYSDATE) values (1200000005,'QC_IB_KOTAK',1200000005,'com.kotak.payment.success.price','1',null,null,null,null,'Y',null,null,null,null,null,null,'NA',null);
Insert into QM_SYS_IB_CONFIGURATION (CONFIGID,APPLICATIONNAME,PARAMID,PARAMNAME,PARAMVALUE,CREATEDBY,CREATED_DATETIME,UPDATEBY,UPDATE_DATETIME,STATUS,MAKER_ID,MAKER_DATE,MAKER_REMARKS,MAKER_SYSDATE,AUTH_ID,AUTH_DATE,AUTH_REMARK,AUTH_SYSDATE) values (1200000006,'QC_IB_KOTAK',1200000006,'com.kotak.payment.failure.price','0',null,null,null,null,'Y',null,null,null,null,null,null,'NA',null);
Insert into QM_SYS_IB_CONFIGURATION (CONFIGID,APPLICATIONNAME,PARAMID,PARAMNAME,PARAMVALUE,CREATEDBY,CREATED_DATETIME,UPDATEBY,UPDATE_DATETIME,STATUS,MAKER_ID,MAKER_DATE,MAKER_REMARKS,MAKER_SYSDATE,AUTH_ID,AUTH_DATE,AUTH_REMARK,AUTH_SYSDATE) values (1200000007,'QC_IB_KOTAK',1200000007,'com.kotak.reversal.success.price','1',null,null,null,null,'Y',null,null,null,null,null,null,'NA',null);
Insert into QM_SYS_IB_CONFIGURATION (CONFIGID,APPLICATIONNAME,PARAMID,PARAMNAME,PARAMVALUE,CREATEDBY,CREATED_DATETIME,UPDATEBY,UPDATE_DATETIME,STATUS,MAKER_ID,MAKER_DATE,MAKER_REMARKS,MAKER_SYSDATE,AUTH_ID,AUTH_DATE,AUTH_REMARK,AUTH_SYSDATE) values (1200000008,'QC_IB_KOTAK',1200000008,'com.kotak.reversal.failure.price','0',null,null,null,null,'Y',null,null,null,null,null,null,'NA',null);
Insert into QM_SYS_IB_CONFIGURATION (CONFIGID,APPLICATIONNAME,PARAMID,PARAMNAME,PARAMVALUE,CREATEDBY,CREATED_DATETIME,UPDATEBY,UPDATE_DATETIME,STATUS,MAKER_ID,MAKER_DATE,MAKER_REMARKS,MAKER_SYSDATE,AUTH_ID,AUTH_DATE,AUTH_REMARK,AUTH_SYSDATE) values (1200000009,'QC_IB_KOTAK',1200000009,'com.kotak.logo.qc','D:\\opt\\Logger\\KotakLogo\\qc.png',null,null,null,null,'Y',null,null,null,null,null,null,'NA',null);
Insert into QM_SYS_IB_CONFIGURATION (CONFIGID,APPLICATIONNAME,PARAMID,PARAMNAME,PARAMVALUE,CREATEDBY,CREATED_DATETIME,UPDATEBY,UPDATE_DATETIME,STATUS,MAKER_ID,MAKER_DATE,MAKER_REMARKS,MAKER_SYSDATE,AUTH_ID,AUTH_DATE,AUTH_REMARK,AUTH_SYSDATE) values (1200000010,'QC_IB_KOTAK',1200000010,'com.karza.logo.qc','D:\\opt\\Logger\\KotakLogo\\qc.png',null,null,null,null,'Y',null,null,null,null,null,null,'NA',null);


select * from QM_SYS_IB_CONFIGURATION;