 CREATE TABLE QC_IB_CONFIGURATION 
   (	CONFIGID NUMBER(10,0) NOT NULL ENABLE, 
	APPLICATIONNAME VARCHAR2(50 BYTE), 
	PARAMID NUMBER(10,0), 
	PARAMNAME VARCHAR2(50 BYTE), 
	PARAMVALUE VARCHAR2(500 BYTE), 
	CREATEDBY NUMBER(10,0), 
	CREATED_DATETIME DATE, 
	UPDATEBY NUMBER(10,0), 
	UPDATE_DATETIME DATE, 
	STATUS VARCHAR2(1 BYTE), 
	MAKER_ID NUMBER(10,0), 
	MAKER_DATE DATE, 
	MAKER_REMARKS VARCHAR2(50 BYTE), 
	MAKER_SYSDATE DATE, 
	AUTH_ID NUMBER(10,0), 
	AUTH_DATE DATE, 
	AUTH_REMARK VARCHAR2(50 BYTE), 
	AUTH_SYSDATE DATE
   );
commit;   
 